apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-ibkd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-ibkd
    app.kubernetes.io/part-of: test-app-khvw
  name: test-component-ibkd
  namespace: build-e2e-hacbs-mdgf
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-ibkd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-ibkd
    spec:
      containers:
      - image: quay.io/mkovarik/test-images@sha256:62926fbb6edaedc9c24ad157e7033835a1ce0157a7418da3ac903084202cee24
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
